### ISSUE TITLE
Surround with function not repeated with `.`

### ISSUE THREAD

**Issue by moll** [tpope/vim-surround#106]
Hey,

Repeating a surround of `yswf` to wrap the word with a function call does not work properly and leaves you in the function input stage again.

**Comment by Iambecomeroot** [comment]
I know that this is an old issue, but is it possible to tie into this special case from my vimrc? For example, I have the following in my vimrc to surround with a latex macro:

```
let g:surround_{char2nr('l')} = "\\\1LaTeX macro\1{\r}"
```

When I repeat it with `.`, it asks me the latex macro name again.
