### ISSUE TITLE
Feature request adding a bit of zencoding

### ISSUE THREAD

**Issue by rockneverdies55** [tpope/vim-surround#111]
Is it possible to add basic functionality of zencoding (emmet) stuff. 

For example; when I want to wrap with a tag, if I can type `div.wrapper` instead of `<div class="wrapper">` it would've been nicer.

Thanks for the great job.

**Comment by fvictorio** [comment]
Any chance to make it work with https://github.com/mattn/emmet-vim somewhere in the future?
