### ISSUE TITLE
Change surround does not work - incompatible with other plugins ?

### ISSUE THREAD

**Issue by pmalek** [tpope/vim-surround#117]
I have a problem where I cannot change any "surround" with this plugin maybe there is something wrong with other plugins that I have installed. 

My `.vimrc`

```
set nocompatible               " be iMproved 

"  -------------------------------------
" --------------- VUNDLE ----------------
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

set encoding=utf-8

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'

" My Bundles here:
" original repos on github
Bundle 'bling/vim-airline'
let g:airline_powerline_fonts = 1
let g:airline_theme='powerlineish'
let g:Powerline_symbols = 'fancy'
Bundle 'scrooloose/syntastic'
let g:syntastic_jslint_checkers=['jshint']
let g:syntastic_check_on_open=1
let g:syntastic_enable_signs=1
Bundle 'altercation/vim-colors-solarized'
Bundle 'tpope/vim-sensible'
Bundle 'tpope/vim-surround'
Bundle 'jiangmiao/auto-pairs'
Bundle 'elzr/vim-json'
Bundle 'HTML-AutoCloseTag'
Bundle 'digitaltoad/vim-jade'
Bundle 'scrooloose/nerdtree'
Bundle 'edkolev/tmuxline.vim'

" vim-scripts repos
Bundle 'AutoComplPop'
Bundle 'L9'
Bundle 'FuzzyFinder'
Bundle 'xmledit'
" --------------- VUNDLE ----------------
"  -------------------------------------

filetype plugin indent on     " required!
syntax on

let g:loaded_matchit = 1

" Solarized theme
let g:solarized_termtrans=1
set background=dark
let g:solarized_termcolors=256
colorscheme solarized

set incsearch
set number
set shiftwidth=2
set tabstop=2
set expandtab
set hls
set timeoutlen=1
set ttimeoutlen=1
set backspace=2

" pretty-print JSON files
autocmd BufRead,BufNewFile *.json set filetype=json
autocmd BufRead,BufNewFile *.html set filetype=html
" json.vim is here: http://www.vim.org/scripts/script.php?script_id=1945
"autocmd Syntax json sou ~/.vim/syntax/json.vim
" json_reformat is part of yajl: http://lloyd.github.com/yajl/
"autocmd FileType json set equalprg=json_reformat
"
" prettify for javascript
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
"au FileType html,xhtml,xml so ~/.vim/bundle/HTML-AutoCloseTag/ftplugin/html_autoclosetag.vim
"au FileType html,xhtml,xml so ~/.vim/bundle/vim-autoclose/plugin/AutoClose.vim

autocmd FileType java %g/\/\*/normal! zf%
autocmd FileType java setlocal foldmethod=syntax
" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

" Always show statusline
set laststatus=2

" mappings 
imap <C-Space> <C-x><C-o>
imap <C-@> <C-Space>
inoremap <F2> <Esc>:w<CR>
noremap <F2> <Esc>:w<CR>
inoremap <F3> <Esc>:wq<CR>
noremap <F3> <Esc>:wq<CR>
inoremap <F4> <Esc>:q!<CR>
noremap <F4> <Esc>:q!<CR>
set pastetoggle=<F5>
noremap <F6> <Esc>:tabe 
inoremap <F6> <Esc>:tabe 
noremap <F7> <Esc>:tabp<CR>
inoremap <F7> <Esc>:tabp<CR>
noremap <F8> <Esc>:tabn<CR>
inoremap <F8> <Esc>:tabn<CR>
noremap <F9> <Esc>:tabc<CR>
inoremap <F9> <Esc>:tabc<CR>
"imap <Esc> <Esc><Esc>

map Q <Nop>
noremap % v%
inoremap <C-e> <End>

set updatetime=400

map <C-n> :NERDTreeToggle<CR>
"autocmd vimenter * NERDTree
```

This is the output of `:map` in `vim` 

```
v  ["          *@:<C-U>exe "normal! gv"|call search('\%(^\s*".*\n\)\%(^\s*"\)\@!', "bW")<CR>
n  ["          *@:call search('\%(^\s*".*\n\)\%(^\s*"\)\@!', "bW")<CR>
v  []          *@m':<C-U>exe "normal! gv"|call search('^\s*endf*\%[unction]\>', "bW")<CR>
n  []          *@m':call search('^\s*endf*\%[unction]\>', "bW")<CR>
v  [[          *@m':<C-U>exe "normal! gv"|call search('^\s*fu\%[nction]\>', "bW")<CR>
n  [[          *@m':call search('^\s*fu\%[nction]\>', "bW")<CR>
v  ]"          *@:<C-U>exe "normal! gv"|call search('^\(\s*".*\n\)\@<!\(\s*"\)', "W")<CR>
n  ]"          *@:call search('^\(\s*".*\n\)\@<!\(\s*"\)', "W")<CR>
v  ][          *@m':<C-U>exe "normal! gv"|call search('^\s*endf*\%[unction]\>', "W")<CR>
n  ][          *@m':call search('^\s*endf*\%[unction]\>', "W")<CR>
v  ]]          *@m':<C-U>exe "normal! gv"|call search('^\s*fu\%[nction]\>', "W")<CR>
n  ]]          *@m':call search('^\s*fu\%[nction]\>', "W")<CR>
   î           *@:call AutoPairsJump()<CR>
   ð           *@:call AutoPairsToggle()<CR>
n  <C-L>       * :nohlsearch<CR><C-L>
   <C-N>         :NERDTreeToggle<CR>
   %           * v%
   Q             <Nop>
n  R           * R<C-R>=<SNR>61_feedPopup()<CR>
x  S             <Plug>VSurround
n  a           * a<C-R>=<SNR>61_feedPopup()<CR>
n  cs            <Plug>Csurround
n  ds            <Plug>Dsurround
n  gx            <Plug>NetrwBrowseX
x  gS            <Plug>VgSurround
n  i           * i<C-R>=<SNR>61_feedPopup()<CR>
n  ySS           <Plug>YSsurround
n  ySs           <Plug>YSsurround
n  yss           <Plug>Yssurround
n  yS            <Plug>YSurround
n  ys            <Plug>Ysurround
n  <Plug>NetrwBrowseX * :call netrw#NetrwBrowseX(expand("<cWORD>"),0)<CR>
v  <Plug>VgSurround * :<C-U>call <SNR>59_opfunc(visualmode(),visualmode() ==# 'V' ? 0 : 1)<CR>
v  <Plug>VSurround * :<C-U>call <SNR>59_opfunc(visualmode(),visualmode() ==# 'V' ? 1 : 0)<CR>
n  <Plug>YSurround * :<C-U>set opfunc=<SNR>59_opfunc2<CR>g@
n  <Plug>Ysurround * :<C-U>set opfunc=<SNR>59_opfunc<CR>g@
n  <Plug>YSsurround * :<C-U>call <SNR>59_opfunc2(v:count1)<CR>
n  <Plug>Yssurround * :<C-U>call <SNR>59_opfunc(v:count1)<CR>
n  <Plug>Csurround * :<C-U>call <SNR>59_changesurround()<CR>
n  <Plug>Dsurround * :<C-U>call <SNR>59_dosurround(<SNR>59_inputtarget())<CR>
n  <Plug>SurroundRepeat * .
   <F9>        * <Esc>:tabc<CR>
   <F8>        * <Esc>:tabn<CR>
   <F7>        * <Esc>:tabp<CR>
   <F6>        * <Esc>:tabe<Space>
   <F4>        * <Esc>:q!<CR>
   <F3>        * <Esc>:wq<CR>
   <F2>        * <Esc>:w<CR>
```

**Comment by aradunovic** [comment]
I was almost ready to remove the plugin, when I found this issue (don't know how I missed it before). Thank you @kairyu, your solution works perfectly!

**Comment by victoriastuart** [comment]
As both a new-ish Vim user and new to this plugin, I almost gave up on vim-surround working properly on my machine [Arch Linux; vim v.8 via gVim install (Jan 2017: provides a Vim v.8.0 with clipboard support enabled)], with the following plugins installed:

    gundo
    minibufexpl.vim
    nerdtree
    plugin
    supertab
    tcomment_vim
    tlib_vim
    vim-addon-mw-utils
    vim-snipmate
    vim-snippets
    vim-surround

However, vim-surround was 'buggy' for me; particularly, from examples on the main repo page, I could not figure out how to select text in Visual mode and apply vim-surround mappings, without going into Insert mode.  Adding

    set timeout timeoutlen=1000 ttimeoutlen=0

to my .vimrc did not help, or variations, e.g.

    set timeout timeoutlen=3000 ttimeoutlen=100

I was just about to give up, but decided to have one last go.  I managed to figure it out (at least for me / my machine / my configurations; YMMV).

1. To quote a single word, while in Normal mode position your cursor at or in the word, and press

    ysiw"

to double-quote the word:

    apple >> "apple"

Forget about using

    css"

etc. as in my experience it sometimes works, but mostly does not work (well).  Particularly, I can't use it [ css" ] in Visual mode on selected text. It [ css" ] may be useful sometimes, e.g. for double-quoting a list of words at the beginning and the end of the multi-line list (though that is not very useful, and there are better options, below).

2. To change that quotation, "apple", while in Normal mode with the cursor inside the quoted word, type any of the following:

    cs"'    : change "apple" to 'apple'
    cs'{    : change 'apple' to {apple}
    etc.

3. To delete a quotation, while in Normal mode with the cursor inside the quoted word, type

    ds{     : change {apple} to apple

4. To double-quote a line, apply  this:

    yss"    : This is a line. >> "This is a line."

5. Lastly, to quote multiple words, regions of selected text, ... select the text region in Visual mode, and type

    S"      : NOTE!! Capital S, here (only)!

Example:

    "Apple banana" carrot
    
        Type V  [visual mode; cursor at beginning of Apple]
        Type we [shortcut to select two words: Apple banana]
        Type S"

    "Apple banana" carrot

Q.E.D.  :-)

**Comment by ArtStepanyuk** [comment]
Same for me cs' doesn't do anything but ysiw' works just gret 

Thanks @victoriastuart

**Comment by graywh** [comment]
@ArtStepanyuk `cs'` is not a complete command, so it *shouldn't* do anything

@victoriastuart In Normal mode, `css"` should surround a "sentence" with double quotes.  This plugin doesn't have any Visual mode maps starting with `c`.  (The only maps this plugin makes in Visual mode are `S` and `gS`.)

**Comment by pmalek** [comment]
Nevertheless, I do think that we can close this issue as my original problem has been resolved quite some time already.

@victoriastuart nice sum up though :)

**Comment by Piping** [comment]
@tpope  I think @victoriastuart 's sum up is really good for beginner. The README.md is not very easy to follow. Use his sum up!

**Comment by victoriastuart** [comment]
... HER writeup ...

**Comment by dewrich** [comment]
I just remapped `cs` in my .vimrc so that the directions lined up like this:
```    
map cs ysiw
```

**Comment by graywh** [comment]
@dewrich `cs` is a command added by this plugin.  By re-mapping it, you will lose that ability (to change a surrounding to a different surrounding).

**Comment by dewrich** [comment]
@graywh thx, gtk
