### ISSUE TITLE
surround with a space

### ISSUE THREAD

**Issue by nilsbecker** [tpope/vim-surround#123]
i often want to surround crammed binary operators with a single space. first i tried `vS<space>` which did not work, just as `vS<space><cr>`. by wild guessing i tried `vSs` which seemed to work at first. looking at the source, it became clear that these bindings really work like this, but i don't understand why surrounding with space is not easy? is there maybe a typo in one of these binding? what else should i do?

**Comment by jsatk** [comment]
I just spent a ton of time attempting to figure this out. Thanks for putting the answer here!

@tpope would you be opposed to me adding a blurb about this in the examples? I can see this being very useful for folks changing `var foo=1` to `var foo = 1`.
