### ISSUE TITLE
What does the "y" stand for in "ysiw"?

### ISSUE THREAD

**Issue by neagle** [tpope/vim-surround#128]
If a genie gave me only one wish, rather than wealth or peace on earth or immortality, I would wish for all documentation to include the words letters are intended to match when there are one-letter commands.

For instance, what does the "y" in "ys<sup>urround</sup>i<sup>nsert</sup>w<sup>word</sup>? I'm sure it's something obvious. But the fact that I can't figure it out makes it hard to remember.

And, am I totally alone, or would it be a lovely addition to the README to list these for all the relevant commands?

**Comment by BatmanAoD** [comment]
This confused me greatly as well, since `y` is by now semi-permanently associated with `yank` in my mind. Why not, say, `ss`, for "(insert) surround"? (The "insert" is silent, kind of like in "cc = change (line)".) Of course, this would conflict with the `s` mapping described [here](http://vim.wikia.com/wiki/Insert_a_single_character), but at least it doesn't conflict with any built-in Vim-isms.

**Comment by tpope** [comment]
I'm not going to **override** existing functionality over a nitpick with a mnemonic.  This no more a conflict than Vim's own diff-put `dp` conflicts with delete `d`.

**Comment by BatmanAoD** [comment]
I guess I don't think of Wiki tips as existing functionality, though I do have that particular mapping in my personal `.vimrc`.

**Comment by tommcdo** [comment]
`s` is a built-in command in Vim. It deletes `[count]` characters and enters Insert mode.

The Wiki is suggesting that you can override that behaviour.

**Comment by BatmanAoD** [comment]
@tommcdo Ah, I didn't even realize that. Thanks.

**Comment by Chinggis6** [comment]
(I think) It's for `yank`, yank surrounding inner word (to a register or somewhere else to make things on it after, such as surrounding with characters (adding characters around)).

It is very consistent with Vim's other key bindings.

Consider `csw`, `dsiw` for change and delete.

There's also `ysl` to yank surround letter (see also Vim's own `dl` (with `x` shortcut), `yl` commands).

To keep things neater one can press <kbd>v</kbd> into Visual Mode and use `S` to surround visually selected text, with any combination, for ease.

For more information consider looking up `:help text-object`.

**Comment by Hultner** [comment]
Is it just me or wouldn't it be nice to have `gs` instead as in "go surrond", seems more consistent with other plugins such as vim-commentary.

**Comment by RoryNesbitt** [comment]
I agree that this is a very minor issue and it's probably more confusing to change now that just live with it.

That being said, i<sup>nsert</sup>s<sup>urround</sup> or a<sup>dd</sup>s<sup>urround</sup> would make more sense with the accompanying d<sup>elete</sup>s<sup>urround</sup> and c<sup>hange</sup>s<sup>urround</sup>

**Comment by TisnKu** [comment]
I am reading it as "yield surrounding x".

**Comment by b4tg5s** [comment]
I am reading it as "Yes, surround!". Does not help to remember it either.

**Comment by tpope** [comment]
No need to overthink it. In Vim, `d`, `c`, and `y` are the 3 big operations. In surround.vim, `ds`, `cs`, and `ys` are the 3 big operations.
