### ISSUE TITLE
Issue using Surround alongside CtrlP

### ISSUE THREAD

**Issue by Integralist** [tpope/vim-surround#129]
Note: the below issue resolves itself if I uninstall vim-surround.

If I do a CtrlP search for the file `tabloid/webapp/static/sass/services/zhongwen/wide.scss` then that plugin stops matching at `tabloid/webapp/static/sass/services/zhongwen/wide.s`, so the final `css` of the file name is not matched for some reason?

If I then hit any other key (e.g. an arrow key) I'll get the following error...

```
Error detected while processing function <SNR>73_changesurround..<SNR>73_dosurround:
line 41:
E21: Cannot make changes, 'modifiable' is off
```

If I uninstall vim-surround then the problem goes away.

cc @kien in case he is aware of this issue?

My Vim configuration file can be seen here: https://github.com/Integralist/Fresh-Install/blob/master/Shell/.vimrc

Any ideas on how I can resolve this issue?

**Comment by jsit** [comment]
@tpope I'm an intermediate Vimscript writer who's vexed by this conflict -- Can you please elaborate if you can on _where_ this `<nowait>` would have to be added in CtrlP.vim? I'd love to solve this. Thanks.
