### ISSUE TITLE
Surround with newlines?

### ISSUE THREAD

**Issue by firedev** [tpope/vim-surround#140]
Given:

```
FactoryGirl.create_list(▌ .... ) do |model|
```

And pressing `yst)<cr>` I would expect:

```
FactoryGirl.create_list(
  ▌ ....
) do |model|
```

Instead I see:

```
FactoryGirl.create_list(^M ....^M) do |model|
```

**Comment by unphased** [comment]
I would love it if we could get `^M` to also do what `^J` does in this situation.

**Comment by BohrShaw** [comment]
It works by defining a custom replacement:

    " `char2nr("\<CR>")` == 13
    let g:surround_13 = "\n\r\n"

**Comment by akarzim** [comment]
@firedev : You can consider this way to achieve your goal : `cS((` or `cSbb`.
The `S` instead of `s` will indent the surrounded text and place it on a line of its own.

**Comment by firedev** [comment]
Thank you, wasn't aware of `S`. Guess have to re-read the docs. 

Pardon my ignorance, what `bb` means in this scenario?

**Comment by akarzim** [comment]
`bBra` are aliases for `({[<`.

**Comment by unphased** [comment]
It's a bit uncomfortable to have to carefully press the Shift key to get the capital S here. But `cSBB` or `cSbb` are cool tricks, thanks for the tip. 

What it does is "`c`hange" "`S`urrounding (line-wise)" "`b`rackets" for "`b`rackets" and as part of the surrounding operation it does filter it through `=`.

**Comment by lukelbd** [comment]
Adding the following custom surround delimiter definition to my `.vimrc` works perfectly for me:

```vim
let g:surround_{char2nr("\<CR>")} = "\n\r\n"
```

Above, `"\<CR>"` is a literal carriage return, used when you press Enter as the surround delimiter. If this solution has no side effects, I think this issue can be closed.

**Comment by tpope** [comment]
Good enough.
