### ISSUE TITLE
Feature request: Django/Jinja/Liquid/etc. template tag awareness

### ISSUE THREAD

**Issue by erikrw** [tpope/vim-surround#143]
I made this to insert Django/etc. template tags:

``` vim
let b:surround_{char2nr('d')} = "{% \1{% \1 %}\r{% end\1\r .*\r\1 %}"
```

For example, `ySSdfor item in items<cr>` turns

``` html+django
<li>{{ item }}</li>
```

into

``` html+django
{% for item in items %}
    <li>{{ item }}</li>
{% endfor %}
```

Would it be doable to add awareness for changing/deleting surrounding tags as well?

**Comment by sassanh** [comment]
Thanks for this fantastic plugin. It eases using vim so much.
It'd be great if you could add support for Django/Jinja, currently I'm using the above line in my vimrc, but native support would be appreciated.
