### ISSUE TITLE
Add "space" target

### ISSUE THREAD

**Issue by rosshadden** [tpope/vim-surround#154]
I think "space" should be a target.  By which i mean the space character, not necessarily all whitespace.

It would be useful to be able to delete the spaces in the following example (where `|` denotes the cursor):

```
<h1> te|st </h1>
```

I've been through the docs to see if this is possible, but don't think it is.

**Comment by tommcdo** [comment]
With the different types of brackets, the left includes space padding and the right does not. So for text like this:

   ( this is some text )

you can remove the spaces with `cs()`. I'm not sure if this is implemented with tags, but it seems like a feasible feature to add if not.

**Comment by tpope** [comment]
Yeah, there's no HTML support mainly because there's no obvious mapping to put it on, but you could probably stick it on `T` or something.

**Comment by tpope** [comment]
On second thought, it's not that simple because you'd need to re-enter the tag. I'm really struggling to see the need for this in the HTML case because I've never seen anyone put space inside the tag like that. And space as a target would only work if there was a single word in the tag, so I'm deeming that pretty contrived as well.

**Comment by rosshadden** [comment]
The HTML was just an example; let me try a better explanation.  Consider the following situation:

```js
if(fo|o === "bar"){
    // ...
}
```

If you wanted to add spaces around the parenthesis, because what is currently there looks like crap, you can easily do that via `ysa(  ` (with two spaces at the end).  However, you cannot really do the inverse.  I've found myself on several occasions trying `ds  ` (again with two spaces) which seems to be intuitive, but is unsupported.

Hopefully what I'm asking about is more clear now.  It's much more universal than tags or brackets, etc.

**Comment by tpope** [comment]
As explained above, `cs()` works for spaces in parentheses.

**Comment by rosshadden** [comment]
Yes `cs()` works for spaces _in_ parentheses, but what about _around_ parentheses (for example)?  More generally, around any target currently supported by the plugin.

**Comment by tpope** [comment]
How exactly do you propose it figures out *which* spaces you're thinking of? In your last example it could just as easily delete the spaces around the `===`.

**Comment by rosshadden** [comment]
Yeah that's a great point that I had not considered.  The only (admittedly not well thought-out) solution I can come up with would be to instead add something like `cs<space>()`, which would change `" (foo) "` to `"(foo)"`.  That's already how `<space>` seems to work in vim-surround, where it's more of a modifier for what comes after it.

**Comment by tpope** [comment]
I think spaces outside parentheses is pretty contrived in general, but you can do `ysa)<Space><Space>` to achieve it.

**Comment by rosshadden** [comment]
I'm really talking about the inverse of `ysa)<space><space>`, which is deleting (or changing) the spaces, and is not currently achievable as far as I know.  I'm just proposing it for completeness, for balancing out something that is already supported (adding spaces around things) to something that is not (removing or changing spaces around things).

Obviously as the owner of the project, if you think it's contrived than that's fair enough!  I will say that I feel like it's not really about being a common case or not in my mind, but rather about having a strong featureset so that users can solve as many problems as they can with similar, composable mechanics.

Anyway, thanks for your time.

**Comment by namark** [comment]
Yea, I stumbled upon this too in a scenario like this:
code: y = a +bbb+ c;
me: haha! an opportunity! ysw<space><space> on bbb
code: y = a + bbb + c;
me: yes! perfect!... hmmm... naah, who said things should be spaced like that? I want it more compact in this particular case so let's go ds<space><space>ds<space><space>, and I should get y = a+bbb+c, then might even do another one on = sign
code: y = a + bbb + c;
me: ...  ds<space><space>
code: y = a + bbb + c;
me: ... ahh, the inhumanity :'( ... Fyf<space>x;.;.;.;.;.

So, yea, that's my gripe... might not make any sense from the point of view of the implementation, but I often find myself wanting to do something like that, intuitively...

**Comment by namark** [comment]
Well, it appears that I was a couple of years behind, and the feature was implemented long ago... so nevermind me... I'm thoroughly embarrassed...

**Comment by ivorpeles** [comment]
@rosshadden I think what you're asking for is achieved by: `ys%<space><space>`.
For me this transformed `if(foo){ bar }` into `if (foo) { bar }`.

**Comment by rosshadden** [comment]
Was it?  If so we can close the issue.  And if not, we can probably still close it.

I still use (and love) surround, but guess I haven't thought about this part of it since I posted my issue.  Which is kind of an argument for it indeed being too contrived, as @tpope had said.
