### ISSUE TITLE
Changing surrounding punctuation with comma doesn't work

### ISSUE THREAD

**Issue by fritzophrenic** [tpope/vim-surround#159]
I just upgraded to version 2.1 to take advantage of the ability to operate on arbitrary punctuation. So now, I can change lists separated by commas, to semicolons with "cs,;".

But the opposite, "cs;,", doesn't work. It treats the comma as opening an xml-like tag instead for some reason (i.e. equivalent to '<').

Perhaps this is just my setup, I did not spend much time at all with debugging.

**Comment by tpope** [comment]
Oh, I think comma is special cased as a lazy way to avoid typing shift for `<`. Feel free to hunt that down and nuke it.

**Comment by sunaku** [comment]
:boar: Hunted down in pull request #167.  :checkered_flag: Please review and merge!

**Comment by yuex** [comment]
I think it's better to provide configuration interfaces and let the user decide whether to use such kind of a-little-bit-special characters. But I think the use of `ctrl` modified key will be okay. I partially fix this issue by enable file type checking for such kind of special keys in PR#174. In most cases it will fix this issue while not affecting the users who get used to using `,`.
