### ISSUE TITLE
Request: Option to change the extra space behavior to closing brackets instead of opening

### ISSUE THREAD

**Issue by tbttfox** [tpope/vim-surround#168]
I almost always use ysw( but it adds those extra spaces.  I know I *should* type ysw) but I can't get my fingers to cooperate. I think it's because the cursor is sitting at the beginning of the word.

Is there any way to add an option that would swap the behavior of the different types of brackets? So that )}] will add the extra space instead of ({[ ?

**Comment by tpope** [comment]
No, but you can override them one by one. My recommendation is just to use `yswb` instead; it's easier to type.

**Comment by 0xMH** [comment]
Wanted to add that you could use these targets b, B, r, which are aliases for ), }, ].
so 
```
yswb > (foo)
yswB > {foo}
yswr > [foo]
```

**Comment by mohkale** [comment]
Did anyone actually get round to doing this in a fork? I've swapped the behaviour as you've described in [evil-surround](https://github.com/emacs-evil/evil-surround) and I'd like to do so in this as well but I can't for the life of me grok where/what I need to change.
