### ISSUE TITLE
Bug: all delimiters are escaped by backslashes

### ISSUE THREAD

**Issue by strburst** [tpope/vim-surround#170]
Anything with a backslash before it is ignored in mappings like `ds` and `cs`. E.g. if the * indicates the cursor position, and `ds(` or `ds[` is entered:

`\(he*llo)` -> `\(he*llo)` (no change)
`\[he*llo]` -> `\[he*llo]` (no change)
`(lalala\(hm*m))` -> `*lalala\(hmm)`

I encountered this while writing a lambda expression in Haskell:

```haskell
binTree3 = foldl (\(, *item) -> addBinTree item tree) BinEmpty [4,1,6,2,5,12]
```

I had written the lambda expression with an extra parameter, so I was trying to get rid of the extra `()`, which aren't needed for lambda expression with a single parameter.

This behavior might be useful when strings are escaped, like `'can\'t'`, but probably not with parens or other things. I was very surprised when it happened.

**Comment by tpope** [comment]
This has to do with how the `i)` and `a)` text objects themselves work. I don't think it can be fixed with the current surround implementation.

**Comment by strburst** [comment]
Aww. Ok, not much else to say about it then.
