### ISSUE TITLE
Keymap collision with vim-colemak

### ISSUE THREAD

**Issue by jacklenox** [tpope/vim-surround#171]
If anyone can help me with this I'd be really grateful.

I have noticed that `vim-surround` has a keymap collision with the `vim-colemak` plugin. The `vim-colemak` plugin maps the forward word (normally `w`) key to `y`. This means that when trying to scroll forward a word at a time, Vim keeps entering operator pending mode, and then waits before moving forward by a word..

There's [a workaround](https://github.com/jooize/vim-colemak#issues) on the `vim-colemak` page for dealing with a similar keymap collision with `vim-fugitive`.

If anyone can help me with an equivalent fix for `vim-surround`, that would be amazing. I'm still fairly new to Vim and my attempts so far have not been fruitful.

I've also [reported this issue](https://github.com/jooize/vim-colemak/issues/2) on the `vim-colemak` repo but I haven't heard anything since posting and it looks a bit dormant over there.

**Comment by tpope** [comment]
You can set `g:surround_no_mappings` and then recreate the maps in whatever way you like.

**Comment by jacklenox** [comment]
Ah, thanks Tim! [All sorted now](https://github.com/jooize/vim-colemak/issues/2).
