### ISSUE TITLE
Detect correct surrounding quotes to change/delete in ruby

### ISSUE THREAD

**Issue by zubin** [tpope/vim-surround#178]
Given this ruby code:

``` ruby
puts %{The status is '#{status.gsub('_', ' ')}'}
```

When the cursor is on `#`, `cs'"` should change the outer single quotes. Similarly, `ds'` should delete the outer single quotes.

ie it should detect that the first quote is outside the string interpolation and look for a matching one after it.

**Comment by graywh** [comment]
Because the same character is used to start and end, auto detection is unlikely to ever be added.  Vim's text objects using single and double quotes suffer the same issue.

**Comment by zubin** [comment]
This situation is rare, so closing this.
