### ISSUE TITLE
[Question] Replace spaces with parenthesis

### ISSUE THREAD

**Issue by alexlafroscia** [tpope/vim-surround#179]
I keep getting my Ruby and Python mixed up, writing

```ruby
print 'You win!'
```

when I mean to write

```python
print('You win!')
```

Is there some quick way using Surround to replace the space before the string with parenthesis around it?  I've tried every combination I could thing of and can't seem to get it right.

**Comment by tommcdo** [comment]
How would you define where the closing parenthesis should go?

**Comment by tpope** [comment]
Best you can do is something like `f'ys$bX`, which deletes the space after the fact. (The inverse does have special case support: `csbs`)

**Comment by alexlafroscia** [comment]
`ys$b` was just what I was looking for! Just trying to understand it though; what does `$` represent?
