### ISSUE TITLE
Incorrect wrap by <CR>

### ISSUE THREAD

**Issue by unclechu** [tpope/vim-surround#180]
When I try to select (visual mode) `'some text'` in this example:
```text
foo.bar('some text');
```
And press `^S` and `<CR>` I want to see it:
```text
foo.bar(
    'some text'
);
```
But I got this:
```text
foo.bar(^M'some text'^M);
```
Looks like a bug?

**Comment by tpope** [comment]
Less of a bug and more of an incorrect speculation, but sure, please do investigate making that work.

**Comment by fdinoff** [comment]
It does something reasonable. `<CR>` is `^M` (Or ascii 13). You told it to surround it with carriage returns and it did. 

If you want newlines (ascii 10) you want to use `^J` to get what you want. (Indentation not included)

**Comment by unclechu** [comment]
@fdinoff thank you! Anyway, I wrote own hack for save indentation https://github.com/unclechu/vimrc2/commit/792aa32950a1efbd2766aeda0caa5783dad60bc3
