### ISSUE TITLE
TeX quotes `'

### ISSUE THREAD

**Issue by Lavvrence** [tpope/vim-surround#182]
Is it possible to make surround work on TeX-style quotes `' ?

**Comment by tpope** [comment]
Yes

**Comment by tpope** [comment]
Halfway that is. Create but not target

**Comment by Lavvrence** [comment]
Sorry, I couldn't find anything in the documentation. Could you elaborate? Doing ysiw' on a word encloses it in two ' and the same is true of ysiw`.
