### ISSUE TITLE
surrounding quoted text inserts a space in the wrong place

### ISSUE THREAD

**Issue by yannack** [tpope/vim-surround#184]
Start off with this text:
```
a_dict = {'hello': 'world'}
```
place cursor on "world" and type `ysa']` and the resulting text is
```
a_dict = {'hello':[ 'world']}
```
Notice the space is placed after the opening bracket
instead of expected
```
a_dict = {'hello': ['world']}
```
with space before opening bracket.
I am not sure if my expectations are unjustified however :)

**Comment by tommcdo** [comment]
That's just how the `a'` text object works. You can use `ys2i']` instead (see `:help i'`).

**Comment by yannack** [comment]
OK, I did not know that, thanks for the tip about 2i', that is really cool
:)
