### ISSUE TITLE
Request: Abilty to yank text between quotes...

### ISSUE THREAD

**Issue by pmorch** [tpope/vim-surround#192]
Say I have this text:

    "This is a 'nested*quote' in an outer quote"

(like in surround.txt, the asterisk (*) is used to denote the cursor position)

Now cs"{ changes that to:

    { This is a 'nested quote' in an outer quote }

Cool. But I'm looking for a way to yank `This is a 'nested quote' in an outer quote` - the stuff inside the surround. Perhaps optionally including the surround characters. Then I could also e.g. yank the entire current `<div>...</div>` for pasting below.

Is this within reason?

**Comment by Chun-Yang** [comment]
`yi{` (yank inside {}) and `yit` (yank inside tag)

**Comment by pmorch** [comment]
Wow, that is standard vim - I had no idea. Documented in [:help object-select](http://vimdoc.sourceforge.net/htmldoc/motion.html#object-select). Thanks!
