### ISSUE TITLE
do...end blocks in ruby

### ISSUE THREAD

**Issue by ballcheck** [tpope/vim-surround#193]
It would be great if you could toggle between {...} and do...end in Ruby.

**Comment by akarzim** [comment]
One way to achieve it partially is to add this line in your `.vimrc`file

```
autocmd FileType ruby let b:surround_45 = "do \r end"
```

Then, `cS{-` or `cSB-` will change

```
it { expect… }
```

to

```
it do
  expect…
end
```

But I didn't found how to do it the reverse way. `cS-B` seems not to work. Any idea ?

**Comment by tpope** [comment]
I recommend https://github.com/AndrewRadev/splitjoin.vim, as getting surround.vim as it currently stands to get the whitespace right is nigh impossible.
