### ISSUE TITLE
Trying ysiw** for markdown files

### ISSUE THREAD

**Issue by voylinux** [tpope/vim-surround#202]
Trying to make ysiw** as a help for markdown files, results in adding only on *.
Am I doing it wrong or isn't that posible right now?

**Comment by tpope** [comment]
Not possible.

**Comment by davidsierradz** [comment]
You can use surround customizing (see: `:h surround-customizing`), for example:

```vimscript
autocmd FileType markdown let b:surround_8364 = "**\r**"
```

8364 is the € symbol (check the symbol number with `:echo char2nr("-")`, now you can use it like:

```
|foo bar
ys2w€
|**foo bar**
```
