### ISSUE TITLE
Customize prompt?

### ISSUE THREAD

**Issue by adriaanzon** [tpope/vim-surround#203]
I'm trying to customize this plugin to surround with [Blade](https://laravel.com/docs/5.2/blade) directives. Blade directives always start with an @ symbol, so for example:

```blade
@if(true)
    ...
@endif
```

I'm referring to [this](https://github.com/tpope/vim-surround/blob/master/doc/surround.txt#L160-L187) section in the documentation, that explains how you can do this.

So I tried it and it works quite well, but one thing annoys me. Since Blade directives always start with an `@`, I'd like the prompt to look like this (with `|` as the cursor position):
```
Blade directive: @|
```

but whatever I do, ": " will always be appended to the prompt. So these two:

```vim
let b:surround_{char2nr("d")} = "@\1Blade directive: \1 \r @end\1\r(.*\r\1"
let b:surround_{char2nr("d")} = "@\1Blade directive\1 \r @end\1\r(.*\r\1"
```

both end up like this: `Blade directive: |`

That means that I'm not able to do this:
```vim
let b:surround_{char2nr("d")} = "@\1Blade directive: @\1 \r @end\1\r(.*\r\1"
```

because that ends up like this: `Blade directive: @: |`

Is there any way to work around this? Maybe change [this](https://github.com/tpope/vim-surround/blob/master/plugin/surround.vim#L94-L95) section to check if there already is a colon somewhere, and if there is, don't append ": ".

**Comment by tpope** [comment]
I would go so far as to say you could only add a colon if the expression ended in a word character `\w`.
