### ISSUE TITLE
Indentation is altered when changing multiline parenthesis

### ISSUE THREAD

**Issue by petersohn** [tpope/vim-surround#206]
Let's start with a new file with the following contents:
```
(
foo
bar
)
```
If I type `cs)}` anywhere inside this block, the indentation changes to the following:
```
{
    foo
        bar
}
```
If now I type cs}), I get the following:
```
(
 foo
 bar
 )
```
With `cs)]`, the result is this:
```
[
    foo
    bar
]
```
Actually, changing from any to either type of parenthesis results in this indentation, regardless of what the original indentation was. If I try the same in a file that has automatic syntax-based indentation (e.g. a Python file), I get even weirder results.

I have `expandtab`, `shiftwidth=4`, `tabstop=4`, `nocindent` and `nosmartindent`. I tried with both `autoindent` and `noautoindent`, the result is the same. With `paste`, tabs are used instead of spaces in the case of `{}` and `[]`.

**Comment by chase** [comment]
@petersohn Have you figured out a workaround for this? I've only just noticed this problem recently, so I'm not sure if it is an issue in recent versions.

**Comment by petersohn** [comment]
The only workaround I could find is to reset the indentation manually afterwards.

**Comment by arowla** [comment]
This is a pretty serious issue. Spacing is also changed, e.g. from `('foo', 'bar')` to `[ 'foo', 'bar' ]`, which is really undesirable, since it can take me as long or longer to put the spacing back, than to change the "surrounds" myself.

**Comment by tpope** [comment]
The default is to automatically reindent with `=` after a multi-line surround. You can disable that with `let g:surround_indent = 0`. But I'd recommend getting to the root of why it's indenting weird to begin with.

Spacing is a function of which bracket you use: `[` vs `]`.

**Comment by jamesob** [comment]
With `let g:surround_indent = 0` in my `.config/nvom/init.vim`:

### Before 

![selection_832](https://user-images.githubusercontent.com/73197/32125204-a7d5fc62-bb1f-11e7-88da-af96dcbdf322.png)

### After `cs{[`

![selection_833](https://user-images.githubusercontent.com/73197/32125197-9eb05f7e-bb1f-11e7-9a1b-6560abad1afa.png)

### Me

![sad ben](http://i0.kym-cdn.com/entries/icons/facebook/000/020/104/People_are_being_mean_by_making_mashups_of_sad_Ben_Affleck_s_reaction_to_Batman_v_Superman_reviews.jpg)

**Comment by amagee-willow** [comment]
Yeah I am also seeing unexpected changes to spacing using both directions of brackets and with and without `let g:surround_indent = 0`.

Even if I comment out the body of the `s:reindent` function I still experience the issue.

**Comment by b3z** [comment]
Why is this closed? Is there a fix? The issue still exists.

**Comment by chase** [comment]
> Why is this closed? Is there a fix? The issue still exists.

If I remember correctly, based on what tpope said, the trick is to use `cs}]` not `cs{[`.

While I was still using Vim instead of Neovim, I believe I switched to vim-sandwich to avoid this.

---

If you're using Neovim you can instead try one of these:
- https://github.com/kylechui/nvim-surround
- https://github.com/echasnovski/mini.nvim#minisurround
- https://github.com/ur4ltz/surround.nvim

**Comment by b3z** [comment]
So I use vim-surround on nvim and the closest you can get is `cSB)` but it still indents the whole block.

**Comment by petersohn** [comment]
The problem still happens when using `cs}]` instead `cs{[`, so that doesn't solve it.

**Comment by contang0** [comment]
I'm working on a single line and still have this issue. I want to wrap `1 / 2` in parentheses by visually selecting the expression and then doing `S(`.

Result:

```
( 1 / 2
 )
```

In Python this will of course break things.

**Comment by tpope** [comment]
> I'm working on a single line and still have this issue. I want to wrap `1 / 2` in parentheses by visually selecting the expression

Do not visually select the newline if you don't want it surrounded.

**Comment by contang0** [comment]
Indeed, seems like v$ also selects the EOL, which I didn't realize until now. I guess I can live with clicking `h` once and then wrapping the parentheses.
