### ISSUE TITLE
Surround with angle brackets

### ISSUE THREAD

**Issue by Jumblemuddle** [tpope/vim-surround#209]
Is there a way to surround text with angle brackets? Not XML tags.

E.g.

ysiw<
This is a| test -> This is <a|> test

**Comment by fvictorio** [comment]
Use `ysiw>`

**Comment by rodorgas** [comment]
Why, though? I always end up here because I forget that in this specific case we use the closing bracket instead of the opening bracket :/

**Comment by fvictorio** [comment]
@rodorgas `ysiw<` is used to wrap something with an HTML element. It prompts you to complete which element to use. For example, you do `ysiw<span>` to wrap the word with a `span` element.

**Comment by d9k** [comment]
> @rodorgas `ysiw<` is used to wrap something with an HTML element. It prompts you to complete which element to use. For example, you do `ysiw<span>` to wrap the word with a `span` element.

мудро
