### ISSUE TITLE
deleting custom surrounds

### ISSUE THREAD

**Issue by ballcheck** [tpope/vim-surround#210]
I have a custom surround `let g:surround_105 = "if \r end"`

Add surround works great with `ySsi` but can't delete with `dsi`

Also can't change custom surrounds with `csi"`

**Comment by tpope** [comment]
This is explicitly documented as unsupported. It's also a good example of *why* it's unsupported, because what you want is the conditional after the `if` to disappear, but there's no way for surround.vim to know that.

**Comment by alerque** [comment]
@tpope Would you be willing to re-evaluate this? I've been running [a fork of this plugin](https://github.com/alerque/vim-surround) for years with a workaround, and reports are [piling up](https://github.com/preservim/vim-textobj-quote/issues/11) on another plugin I maintain suggesting I'm not the only one with issues.

**Comment by tpope** [comment]
I don't want to replace `normal!` with `normal` unconditionally; there are several special cases for things like `ds"` where `i"` and `a"` which have shall we say surprisingly behavior, and a user map would make a complete mess of that. But I would be okay with a version that used `normal!` for the big built-ins (anything with a special case plus parentheses, brackets, etc.) and `:normal` for everything else.

**Comment by tpope** [comment]
I missed that your plugin was literally a quote operator. Does that matter here? Do your `a` operators include adjacent whitespace like the built-in `a"` does?
