### ISSUE TITLE
S in visual mode just does a substitute command

### ISSUE THREAD

**Issue by zweicoder** [tpope/vim-surround#216]
Following the example and I can't get the visual surround to work. Any ideas where I should look at?

**Comment by jpassaro** [comment]
Is the plugin loaded, are the other commands available? Try `:vmap S` to see what the key maps to...

**Comment by zweicoder** [comment]
Yankstack was the culprit. Thanks for the tip :)

**Comment by Tommyb841** [comment]
I'm having an issue with this. S is mapped to <Plug>VSurround. when i try to surround text with a tag it deletes and inserts something else.
