### ISSUE TITLE
cs on { changes line feed when it is in multi-line nexted obj

### ISSUE THREAD

**Issue by zirho** [tpope/vim-surround#219]
Thank you for awesome plugin!

![image](https://cloud.githubusercontent.com/assets/1251296/21436477/8e493ffa-c833-11e6-922d-09cce3f2e1d0.png)

'cs[{

![image](https://cloud.githubusercontent.com/assets/1251296/21436484/a4ca1f56-c833-11e6-96d3-3987f7c3bf46.png)

desirable

![image](https://cloud.githubusercontent.com/assets/1251296/21436513/c6ac6520-c833-11e6-920d-8087bf001234.png)

**Comment by qstrahl** [comment]
Just so you know, `cS[{` does what you want. The way it is now, you have the option of determining which way it should work by issuing `cs` or `cS`, and the results they produce are not contextual - I imagine this is considered a feature.

**Comment by zirho** [comment]
@qstrahl Thank you so much.
