### ISSUE TITLE
Undocumented surround replacements

### ISSUE THREAD

**Issue by mmikeww** [tpope/vim-surround#222]
I would've never known about `yssf` if it weren't for [this reddit post](https://www.reddit.com/r/vim/comments/4sls0w/macro_practice_formatting_images_filenames_into/d5b1ikp/) 

I suggest adding it to the doc file

**Comment by boardfish** [comment]
`f` is a selection in the same way `ysiw` selects the inner word. It doesn't need documenting - it's already mentioned that it's a text object.

**Comment by JonnyRa** [comment]
it's worth knowing/should probably be documented that `:h surround` is a thing!

**Comment by Maelan** [comment]
Here, `f` is not a text object selection provided by plain Vim (such as `iw`), it is indeed a surrounding target provided by this plugin (such as `[`). And indeed it is not documented, and I guess it should be.

    <x, y>    ----[ cs<f main ]---->    main(x, y)

It seems irreversible though, just like user-defined surroundings (#199).
