### ISSUE TITLE
Pathogen Installation trouble?

### ISSUE THREAD

**Issue by Per48edjes** [tpope/vim-surround#231]
I tried installing via Pathogen (note: changing `git://` in the README instructions to `https://` in order to actually complete the installation), and saw all the files were written in the correct places on my local machine...but I can't seem to use this plugin. Also, `:help surround` doesn't work for me.

(Apologies if this is a pretty pedestrian issue -- I'm new to Vim!) 

Thanks, in advance.

**Comment by adelowo** [comment]
@Per48edjes `:Helptags` would fix this.. You have to run this after installing a new plugin..

**Comment by tpope** [comment]
If your issue is more than just docs, you'll need to elaborate.

FYI I don't see `git://` in the README.

**Comment by Per48edjes** [comment]
Sorry for the late response. Thanks @adelowo; forgot to do that. Typical user error! 😅
