### ISSUE TITLE
Can't get remap to work

### ISSUE THREAD

**Issue by zwhitchcox** [tpope/vim-surround#235]
Hi, I'm trying to add my own mapping for the VSurround call, but it's not working.

`vnoremap log<Tab> <Plug>VSurround`

I added this to my `.vimrc`, but when I type `log<Tab>` in visual mode with my text selected, I just get a beep. However, when I use the regular shortcut (S), it works fine. Do you have any idea why this might be? I'm on the latest branch.

**Comment by zwhitchcox** [comment]
Nevermind, figured out I just had to use `vmap` instead of `vnoremap`

**Comment by tpope** [comment]
Use `xnoremap` so you don't screw up select mode.
