### ISSUE TITLE
Is there any new documentation?

### ISSUE THREAD

**Issue by jedrekdomanski** [tpope/vim-surround#244]
Hi,

I've installed it but some things like "Vs" or "VS" or "viws"" no longer work but the documentation still says it does. Is there any new documentation so I can start using it?

**Comment by 9mm** [comment]
Does this relate at all? https://github.com/tpope/vim-surround/issues/245

**Comment by tpope** [comment]
`VS` should work. `Vs` has been supplanted by `VgS`. If any documentation is out of date, please direct me to it.
