### ISSUE TITLE
Surround a line 

### ISSUE THREAD

**Issue by allopislozano** [tpope/vim-surround#246]
Hi there, sometimes I have to surround a line with parentheses. I use visual line selection: VS)   but vim-surround adds unwanted line breaks. Example
input (cursor in the middle):
         A * a = dynamic_cast<B*>(a);
desired output:
         (A * a = dynamic_cast<B*>(a);)
vim-surround output:
  (
   A * a = dynamic_cast<B*>(a);
  )

I defined a line motion doing: xnoremap il g_o0  , but then vim surround won't understand this and will fail to wrap my line contents with parentheses. Anyone knows a good solution?

Cheers!

**Comment by tpope** [comment]
Use `yss)`.
