### ISSUE TITLE
Cursor position after an operation

### ISSUE THREAD

**Issue by MahbubAlam231** [tpope/vim-surround#247]
Say I'm in the line-- Plugin 'tpope/vim-surround' with my cursor at 'P' of 'Plugin'. If I apply ds' the quotes get deleted, also my cursor goes to 't' in 'tpope'. What do I do so that whatever the operation is (cs', cs", ds') after the operation is done the cursor remains in the same place?

**Comment by tpope** [comment]
This behavior is the same as every Vim built-in and is not configurable.
