### ISSUE TITLE
ysiw* with vim-repeatable . produces unexpected output

### ISSUE THREAD

**Issue by shmup** [tpope/vim-surround#249]
given `jared` when I `ysiw` `*` I get `*jared*`, but if I press `.` to repeat I get `***jared*`

given `jared` when I `ysiw` `_` I get `_jared_`, and if I press `.` to repeat I get `__jared__`

but also, if there's a better way to wrap a word in two asterisks, I'd like to know.

(also maybe this is a vim-repeat bug idk)

cheers

**Comment by tpope** [comment]
You'll have to press `l` to get the cursor back onto the word. To make up for the extra keystroke, you can use `csw*` rather than `ysiw*`.

You can define a custom replacement to get 2 asterisks at once.

**Comment by shmup** [comment]
What makes `*` special that it does `***foo*` (requiring me to press l to get back to the word) but `-` or `_` do `--foo--` and `__foo__` ?

I was trying to point out in the issue that it was specifically `*`, sorry if that wasn't clear.

I'm specifically comparing `csw*` `csw*` with `csw-` `csw-`, and their different behavior.

**Comment by tpope** [comment]
Because `_foo_` is a word but `*foo*` is not. `:h word`

**Comment by shmup** [comment]
Doh. Ok, that makes sense.
