### ISSUE TITLE
Bug - any way for i_CTRL-o to work with vim-surround?

### ISSUE THREAD

**Issue by jeffvandyke** [tpope/vim-surround#253]
My scenario: I'm typing along, realized that the word I just typed should have been surrounded in quotes or something, then, from insert mode, I try <kbd>Ctrl-o</kbd> <kbd>ysiw'</kbd>, but this sequence fails after <kbd>i</kbd>, returning to insert mode with "g@i" inserted prior. I'm using repeat.vim.

**Comment by tpope** [comment]
You're lucky, fixing this relates to a change I've been wanting to make anyways.
