### ISSUE TITLE
functionality if cursor is on a surround character

### ISSUE THREAD

**Issue by mkatychev** [tpope/vim-surround#267]
Hi guys, do you have any advice for emulating a particular functionality found in the [atom-vim-mode-plus](https://atom.io/packages/vim-mode-plus) where if a cursor is placed on a particular surround character `<,[,{,(,',"` you would not provide a selection character and only have to provide a replacement character.
Something like this (cursor is on the **bolded** character)

|Old text|Present | Proposed Command|New text|
|-|-|-|-|
| **[​**123+456]/2|`cs])` | `cs)`|**(​**123+456)/2
| **[​**123+456]/2|`ds]` | `ds`|**1**23+456/2

**Comment by tpope** [comment]
What if the cursor is on the `[` but you still want to target the `(`?

**Comment by mkatychev** [comment]
> What if the cursor is on the `[` but you still want to target the `(`?

 I think it's still an acceptable override since moving the cursor right or left should solve that edge case.

**Comment by junkdeck** [comment]
IMO having to remember to move the cursor out the way is not as intuitive as just typing the character you want replaced or removed. You're looking at the same amount of keystrokes, anyway.

**Comment by tpope** [comment]
So every time I want to change a surround I have to look under the cursor and make sure I'm not on top of a different surrounding. This might make sense as a different map but the current proposal isn't going to happen.

**Comment by JeanMertz** [comment]
I was actually looking for this, but as you mentioned @tpope as a _different map_. For example, `ds<space>` or `ds.`. I couldn't find anything in the GH issues or in the documentation, so I guess this hasn't happened yet?

Any thoughts on supporting this as a default map?

**Comment by tpope** [comment]
I was thinking something like `dS`. I guess `ds.` would be fine too. I worry about some day wanting to add "delete surrounding periods" but given the rate of change of this plugin that can probably be ignored.
