### ISSUE TITLE
cs)] in multiline bracketed text results in escaped brackets: \[ \]

### ISSUE THREAD

**Issue by manolomartinez** [tpope/vim-surround#283]
This is probably an interaction with some other plugin, but I am bringing it to your attention anyway, in case it's not, and in case you can help me see what the culprit might be.

If I have a bracketed text spanning two lines

    (hello
     world)

and I do `cs)]` with the cursor, say, on the "e", the result is

    \[hello world\]

and not  

    [hello
     world]

as expected. As I say, probably not vim-surround's fault? But just in case :)

**Comment by tpope** [comment]
That is really strange. I can't reproduce, and am really struggling to see how such a bug would even be possible. Rule out other plugins?

**Comment by manolomartinez** [comment]
Thanks, Tim. Yes, this indeed turns out to be an issue with [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc), which somehow interacts with bracket substitution, I don't fully understand how yet.

Sorry for the noise!
Manolo
