### ISSUE TITLE
Bug when closing delimiter is at line end and open delimiter is after a multi-byte character

### ISSUE THREAD

**Issue by agguser** [tpope/vim-surround#284]
For example, when a line of text is

a→'bc'

, and the cursor is on b, doing ds' causes the line to be

abc→

instead of

a→bc

. Note that when `set virtualedit=onemore`, the bug does not occur.

**Comment by agguser** [comment]
A fix is to change the line
```
  if col("']") == col("$") && col('.') + 1 == col('$')
```
to
```
  if col("']") == col("$") && virtcol('.') + 1 == virtcol('$')
```
. But I'm not sure if this will cause another bug.

**Comment by tpope** [comment]
I'm not sure either, but I'd be willing to merge a PR and find out.

**Comment by agguser** [comment]
It seems that the fix doesn't cause a bug, so I close this issue.
