### ISSUE TITLE
Compatibility with nvim 5.0

### ISSUE THREAD

**Issue by mezeipetister** [tpope/vim-surround#294]
Hi,
I have recently installed nvim5.0-dev and installed your plugin via Plug.
I did read many great articles about vim-surround, but with nvim5.0-dev most of the key bindings does not work.

Do you have any idea?
e.g.: cs"' does not work, as in normal mode, when I press s it means insert mode. If I use shift + S, simple nothing happens.
ds works,
and visual mode change works.

Thank you in advance,
Best wishes,
Peter Mezei.

**Comment by LeoAJ** [comment]
same problem here, I used stable `nvim` 0.4.3 simply install plugin and none of the features works ... I used iTerm2 on latest macOS.

**Comment by murtyjones** [comment]
I'm on nvim v0.5.0 and while the plugin seems to install OK, none of the shortcuts are functioning for me.

**Comment by tpope** [comment]
Can confirm it works on both 0.4.4 and 0.5.0. I'm calling user error all around.
