### ISSUE TITLE
Extending targets

### ISSUE THREAD

**Issue by PROgram52bc** [tpope/vim-surround#301]
In latex, the `\{...\}` pair is usually more useful than `{ ... }`, so I attempted to implement that surrounding pair using something like
```
let g:surround_{char2nr("{")} = "\\{\r\\}"
```
And I noticed that it nicely works with the surrounding commands.

So when I type `VS{`,
```
\vec{u_1}, \vec{u_2}
```
becomes
```
\{
    \vec{u_1}, \vec{u_2}
\}
```

Likewise, typing `cs}{` changes
```
\vec{u_1}
     |
```
into
```
\vec\{u_1\}
    |
```
However, I can't seem to do the reverse with `cs{}`, that "should" change
```
\vec\{u_1\}
      |
```
back into
```
\vec{u_1}
    |
```
I am just curious if there are ways to extend the targets themselves as well, or is that beyond the design decisions?

**Comment by tpope** [comment]
no
