### ISSUE TITLE
Repeat not working for `cs`

### ISSUE THREAD

**Issue by BenjaminRH** [tpope/vim-surround#302]
Repeat functionality for `cs` in normal mode (with `repeat.vim`) doesn't work for me. Other functionality (`ys`, `ds`, etc.) does work.

Currently using vim version 8.2, but have the same problem with other versions (7.4, 8.0).

**Comment by tpope** [comment]
README

**Comment by BenjaminRH** [comment]
The README says

> The `.` command will work with `ds`, `cs`, and `yss` if you install repeat.vim.

I have repeat.vim, and `cs` isn't repeatable. I apologise for being dense, but what am I missing?
