### ISSUE TITLE
Feature request: Adding pipe character to surrounds

### ISSUE THREAD

**Issue by f1sherman** [tpope/vim-surround#305]
Hi there! First of all, thanks for the great plugin, I've used it constantly for years!

When working within the arguments of a ruby block (e.g. `foo do |args|`) I often find myself expecting `vim-surround` to treat the pipes as a surround. Would you be open to adding this?

**Comment by gibfahn** [comment]
From the docs:

> A replacement argument is a single character, and is required by |cs|, |ys|,
> and |vS|.  Undefined replacement characters (with the exception of alphabetic
> characters) default to placing themselves at the beginning and end of the
> destination, which can be useful for characters like / and |.


you can already do this e.g. `ysw|` (assuming you want to do this, vs wanting a text object like `a|` and `i|`, if you want the text object check out https://github.com/kana/vim-textobj-user/wiki)

**Comment by f1sherman** [comment]
@gibfahn thank you!
