### ISSUE TITLE
fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by seanswyi** [tpope/vim-surround#310]
Hi. I'm currently trying to install this but am facing the issue in the title. I'm currently using Vim 8.2 and have had no trouble installing the other plugins I have. Here's my .vimrc file:

```
call plug#begin('~/.vim/plugged')
Plug 'dense-analysis/ale'
Plug 'preservim/nerdtree'
Plug 'tpope/vim-surround'
Plug 'itchyny/lightline.vim'
call plug#end()
```

When I run `:PlugInstall` I get:

```
- Finishing ... Done!
- lightline.vim: Already installed
- ale: Already installed
x vim-surround:
    Cloning into '/home/user/.vim/plugged/vim-surround'...
    fatal: could not read Username for 'https://github.com': terminal prompts disabled
- nerdtree: Already installed
```

I've checked multiple times to make sure that there's not a typo, and have also copy and pasted the correct information but am still getting the error message. Would anyone have any ideas on where I might have gone wrong? Thanks.

**Comment by AlexRainHao** [comment]
Hi, I wondered how you solved it. I encounter it each time I install `vim-surround`, and I have to clone it to plug directory manually, it's really inconvenient.
