### ISSUE TITLE
Extra spaces in brackets for `ys$[` surround

### ISSUE THREAD

**Issue by reckoner** [tpope/vim-surround#314]
with the cursor at `t` and then doing `ys$[`

`this`

I get

`[ this ]`

note the extra spaces. How can I fix this?

**Comment by VladimirMarkelov** [comment]
Opening braces add extra spaces, but closing ones do not. So, use `ys$]`

**Comment by deeperlearner** [comment]
Can I set function be exchanged in vimrc?
That is, `ys$[` for no space and `ys$]` for space.
