### ISSUE TITLE
Indent in linewise editing

### ISSUE THREAD

**Issue by Kipparis** [tpope/vim-surround#317]
Consider I have text: `<em>Hello world!</em>`  
If I select whole line (with `V`) and press `S<p>`, I get:

&lt;p&gt;
&lt;em&gt;Hello world!&lt;/em&gt;
&lt;/p&gt;

(indent is missing)  
The question: how do I make indenting work (it should work, as it is shown in readme),  or do I have possibility after indenting to keep selected section selected, so I can indent it by myself.

P.S. autoindent enabled, smartindent enabled, formatoptions=tcqj

**Comment by AJ-Williams1** [comment]
I believe this is on purpose. I get the same behavior when I use the `<p>` tag, but with any other tag the indentation works. I think that no indentation is just the canonical way to use the `<p>` tag. Please correct me if I am wrong about that.

**Comment by 1wsx10** [comment]
> 
> 
> I believe this is on purpose. I get the same behavior when I use the `<p>` tag, but with any other tag the indentation works. I think that no indentation is just the canonical way to use the `<p>` tag. Please correct me if I am wrong about that.

shouldn't it query the indentexpr for this?

**Comment by tpope** [comment]
The closing tag for `<p>` is technically optional, and the maintainer of `indent/html.vim` has decided this means it shouldn't be indented after, even though literally nobody has deliberately omitted a `</p>` tag since 1997. If you've moved on since the nineties, consider adding this to your vimrc:

```vim
let g:html_indent_inctags = 'body,head,html,tbody,p,li,dt,dd'
```
