### ISSUE TITLE
Undo a custom surround?

### ISSUE THREAD

**Issue by jonahx** [tpope/vim-surround#318]
Apologies if this feature exists, but I wasn't able to figure it out from the docs....

Currently you trigger a custom surround like:

```vim
autocmd FileType php let b:surround_45 = "<?php \r ?>"
```
However, the undo feature `ds-`, which works for builtins like `(`, `{`, etc, does not appear to work for these.  Is this unsupported or am I missing something?

**Comment by tpope** [comment]
Unsupported.
