### ISSUE TITLE
Add support for jinja/django-style surroundings?

### ISSUE THREAD

**Issue by AJ-Williams1** [tpope/vim-surround#319]
I love this plugin, but it would be really cool to have support for jinja/django surroundings such as `{{ }}` and `{% %}`. I may try to implement this myself at some point, but as of now I know very little vimscript.

**Comment by tpope** [comment]
You can add your own with `:help surround-customizing`. I will not be adding native support.

**Comment by tankorsmash** [comment]
@AJ-Williams1 did you get this going? I'm trying to add a custom surround for BQN's `⟨` and `⟩`, and seeing another example of how it'd work with Django tags would be cool. 

The linked docs show how to add a custom mapping via `let b:surround_10216 = "..."`, but its not clear how I'd do something like 'change surrounding [] to ⟨⟩'.

**Comment by AJ-Williams1** [comment]
@tankorsmash Unfortunately I never did, but good luck and if you do figure it out please share in case others find this thread searching.

**Comment by qadzek** [comment]
> support for jinja/django surroundings such as {{ }} 

Try adding the following to your `vimrc`:

```vim
let g:surround_{char2nr('j')} = "{{ \r }}"
```

Note that this will only work for adding surroundings, not for deleting or changing them.

**Comment by tankorsmash** [comment]
That's great, thank you! I must have been confused by it not changing or deleting them. I appreciate it!
