### ISSUE TITLE
This case `csi"'` doesn't work.

### ISSUE THREAD

**Issue by nyngwang** [tpope/vim-surround#324]
For case:

    (&filetype=="fern"<bar><bar> &filetype==""? "" : ":w\<CR>")

cursor on the on any character of `fern`, then type

    csiw"'

or `csiw'`, `cst'` all do nothing.

**Comment by TornaxO7** [comment]
It works for me, if I type `cs"'` instead.

**Comment by tpope** [comment]
`cs"'` is correct.
