### ISSUE TITLE
Wiki characters not supported in font

### ISSUE THREAD

**Issue by mbpowers** [tpope/vim-surround#337]
This is not a problem with the plugin itself but with the symbols used in the wiki not being supported by my font.
![pic-full-screenshots211122-0743-27](https://user-images.githubusercontent.com/45055485/142873774-70aba3df-8846-4fbd-bc38-cdfdcde3db39.png)

I am sure it probably works normally for most, but thought I would put this here in case anyone had a similar issue. I am using the JetBrains Mono Nerd Font. It seems strange that the wiki would use so many characters that aren't supported... is it supposed to use these characters? Is my font broken? If all is as intended, what would be a good font that supports these characters?

**Comment by tpope** [comment]
It's Chinese.
