### ISSUE TITLE
Feature request: allow surrounding with HTML comments

### ISSUE THREAD

**Issue by SiddharthShyniben** [tpope/vim-surround#339]
Currently, we can surround with XML/HTML tags, but surrounding with comments would be awesome.

We _can_ hack it tho. If you try `S<!--` you get:

```html
<!-->
...
</!-->
```

Which works, but isn't perfect.

**Comment by tpope** [comment]
Supported with a custom replacement. See also [ragtag.vim](/tpope/vim-ragtag) which configures this automatically.
