### ISSUE TITLE
newbie can't work it out

### ISSUE THREAD

**Issue by tjallemaal** [tpope/vim-surround#348]
when checking the plugin via` :PlugStatus`, it says OK.

bottom line: The Plugin is installed but the commands don't work ...
I don't know where to look in order to know what's wrong

I have `nvim` installed.
Also, I preinstalled alot of plugins and config stuff from someone else... 

thx for any help

**Comment by tpope** [comment]
Check `:verbose nmap ds` to see if the map actually exists. If it does, it's loaded correctly.

Try the `S` map in visual mode. If that works, you probably have a small `'timeoutlen'` preventing you from using multi-character maps.

**Comment by tjallemaal** [comment]
i typed in the `:verbose` command, this is what it returns:
<img width="905" alt="Screenshot 2022-03-25 at 22 00 16" src="https://user-images.githubusercontent.com/69585777/160200634-64fe2c32-291d-4f73-ba60-9f2120f1d0da.png">

i tried visual mode now. not working either ...

**Comment by tpope** [comment]
> i tried visual mode now. not working either ...

When you press `S` in visual mode, what happens?

**Comment by tjallemaal** [comment]
weird! 
visual mode works now, i dont know what was different yesterday... 
ok, so how do I change 'timeoutlen', do I have to add some line into my config?

**Comment by tpope** [comment]
The default of 1000, aka one second, is fine. Check `:verbose set timeoutlen`, I bet something is overriding it.

**Comment by Halem998** [comment]
OK, 6 months passed and I have to write a new thesis.
I still didn't manage to get it working.

Visual mode works.
But normal mode not. 
`timeoutlen` is 1000; nothing is overriding it, at least I don't notice. 

Any idea maybe?

THX

**Comment by tpope** [comment]
Note that 1000 aka 1 second means you need to input the full map in under a second.

Also, I see vim-sandwich in your screenshot, which appears to be clobbering at least one surround map. Try with it uninstalled to rule out any interference.

**Comment by tjallemaal** [comment]
Uninstalled, still don't work ...

**Comment by tjallemaal** [comment]
" auto-install plugins upon starting
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  "autocmd VimEnter * PlugInstall
  "autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.config/nvim/autoload/plugged')

" TEXT SUPPORT

" LaTeX Support
    Plug 'lervag/vimtex'
    " Plug 'dense-analysis/ale' " LaTeX Linting

" Markdown
    Plug 'gabrielelana/vim-markdown'
    Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
    " Plug 'plasticboy/vim-markdown'    
    " Plug 'godlygeek/tabular'
    
" Pandoc: conflict with markdown auto-indent and syntax highlighting
    " Plug 'vim-pandoc/vim-pandoc'
    " Plug 'vim-pandoc/vim-pandoc-syntax' " Syntax not as good

" Better Syntax Support
    " Plug 'sheerun/vim-polyglot'
    
" Spelling
    " Plug 'kopischke/unite-spell-suggest'

" VimWiki
    " Plug 'vimwiki/vimwiki'

" Templates
    " Plug 'KabbAmine/vBox.vim'
    " Plug 'tibabit/vim-templates'
    " Plug 'aperezdc/vim-template'


" FILE MANAGEMENT

"ADDED BY DJANGO (Rnvimr (rangerintegrationforvim))
    Plug 'kevinhwang91/rnvimr'

" Startup Screen
    "Plug 'mhinz/vim-startify'
    
" File Explorer
    Plug 'ryanoasis/vim-devicons' "adds icons to coc-explorer
    " Plug 'vifm/vifm.vim'
    " Plug 'scrooloose/nerdtree'
    " Plug 'preservim/nerdtree'
    " Plug 'Xuyuanp/nerdtree-git-plugin'
    " Plug 'tsony-tsonev/nerdtree-git-plugin'
    " Plug 'tiagofumo/vim-nerdtree-syntax-highlight' " Is this required?
    
" Fuzzy Finder
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
    " Plug 'jremmen/vim-ripgrep'
    " Plug 'ctrlpvim/ctrlp.vim' " Not as elegant as FZF
    
" Git Integration
    Plug 'mhinz/vim-signify'
    Plug 'airblade/vim-gitgutter'
    " Plug 'tpope/vim-fugitive'
    " Plug 'tpope/vim-rhubarb'
    " Plug 'junegunn/gv.vim'


" AUTOCOMPLETE

" Intellisense
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
      " Keeping up to date with master
      " Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
    Plug 'Shougo/deoplete.nvim', {'do': ':UpdateRemotePlugins' }
    " Plug 'Valloric/YouCompleteMe'
    
" Snippets
    Plug 'SirVer/ultisnips'
    " Plug 'honza/vim-snippets'

" Auto pairs and surround for '(' '[' '{' etc.
    Plug 'jiangmiao/auto-pairs' 
    Plug 'tpope/vim-surround' 
"Plug 'machakann/vim-sandwich' 
    Plug 'tpope/vim-repeat' 
    

" ADDITIONAL FUNCTIONS

" Comments
    Plug 'tpope/vim-commentary'
    " Plug 'jbgutierrez/vim-better-comments'

" Quick Movements in Text
    Plug 'unblevable/quick-scope'
    Plug 'easymotion/vim-easymotion'
    " Plug 'justinmk/vim-sneak'
    
" Terminal
    Plug 'voldikss/vim-floaterm'
    
" Undo tree
    Plug 'mbbill/undotree'
    
" Multiple Cursors
    Plug 'mg979/vim-visual-multi', {'branch': 'master'}
    " Plug 'terryma/vim-multiple-cursors'

" Browser Support
    Plug 'glacambre/firenvim', { 'do': { _ -> firenvim#install(0) } }

" Registers
    " Plug 'gennaro-tedesco/nvim-peekup'

" Zen mode
    " Plug 'junegunn/goyo.vim'

" Look up words
    " Plug 'beloglazov/vim-online-thesaurus'



" MAPPINGS

" Look Up Key Bindings
    Plug 'liuchengxu/vim-which-key'

    

" APPEARANCE

" Themes 
    " Plug 'HerringtonDarkholme/yats.vim' " TS Syntax
    " Plug 'joshdick/onedark.vim'
    
" Status Line
   Plug 'vim-airline/vim-airline'
   Plug 'vim-airline/vim-airline-themes'
    





call plug#end()

" Automatically install missing plugins on startup
autocmd VimEnter *
  \  if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \|   PlugInstall --sync | q
  \| endif

**Comment by Halem998** [comment]
got it now. don't know what it was, prob I was too dumb to hit the right keys
