### ISSUE TITLE
`\032` is needed in more places

### ISSUE THREAD

**Issue by zeertzjq** [tpope/vim-surround#349]
After <https://github.com/tpope/vim-surround/commit/427f80f254da9960230ae8970b6d715e1628a5d9>, `vim-surround` no longer works in Insert mode. In Insert mode a `^Z` is in the place of the closing parenthesis. This means `\032` is needed in more places. Also, some places may need to match both `\r` and `\032` for backward-compatibility.

**Comment by tpope** [comment]
I think I got the right places, I just forgot that `\000` octal literals don't work in regexps. Unclear how I managed to successfully test this.

The rest of the `\r` literals are for the `g:surround_123` configuration mechanism and shouldn't make it into the buffer. I think.  This code is very old.
