### ISSUE TITLE
Autocompletion for tags surrounding

### ISSUE THREAD

**Issue by timsofteng** [tpope/vim-surround#351]
I use vim-surround daily and it's awesome.
But tags wrapping is slightly annoying without autocompletion to type long jsx tags.
Is it any ability to invoke my autocompletion engine during tags wrapping?

**Comment by tpope** [comment]
This is not supported. We use `input()` to get the tag name, so in theory the plugin could be changed to support some sort of completion here. But we're not in insert mode, so it would be more complicated than just calling your usual autocompletion.
