### ISSUE TITLE
Strange symbols appear when surrounding text

### ISSUE THREAD

**Issue by cristobaltapia** [tpope/vim-surround#352]
Hi,

I have been experiencing a strange bug since a couple of days. When surrounding text with `(...)`, `"..."` or `'...'` some unwanted characters are added. I use neovim 0.7.0 in Archlinux.

For example:

```
Hello World!
```

Placing the cursor on `Hello` and pressing `ysiw)` results in the following
```
<80><fc>^B)Hello<80><fc>^B) World!
```

Strangely enough, when doing the equivalent `ysiwb` (`b` instead of `)`) it works normally. What could be causing this behavior?

**Comment by tpope** [comment]
I don't know, but see #313.

**Comment by cristobaltapia** [comment]
Oh! Thanks for that hint! I didn't find it when looking for existing issues. That is my problem, so it has to do with my terminal (foot) and the new version of neovim.

**Comment by dnkl** [comment]
It's been fixed in the latest release of [foot](https://codeberg.org/dnkl/foot/releases/tag/1.12.0). You can either compile it yourself, or wait for your distro to update its package :)

**Comment by cristobaltapia** [comment]
Thanks!
