### ISSUE TITLE
Is there a command to toggle a specific type of delimiter?

### ISSUE THREAD

**Issue by devkvlt** [tpope/vim-surround#357]
Let's say the command is `t"` (for `""` delimiters) and we have cursor on `hello`, how can we achieve the following?
Hit `t"` --> `"hello"`
Hit again `t"` --> `hello`
And again --> `"hello"`

**Comment by andmis** [comment]
What would you expect the behavior of `t"` to be in these cases?
- `"Hello" world "goodbye"`, with the cursor on the `w`
- `"[Hello]"`, with the cursor on the `e`

Seems like there are probably a lot of edge cases, actually.

**Comment by devkvlt** [comment]
First one: `"Hello" "world" "goodbye"` (not `"Hello world goodbye"` because action should be performed against the inner word..)
Second one: `"["Hello"]"` (because `[` and `]` are not part of the inner word.

To be honest, there isn't much benefit to this and it also presents many ambiguous edge cases as you said. So I guess I'll close this issue for now.
