### ISSUE TITLE
[Feature Request] Support wide characters such as `『』`

### ISSUE THREAD

**Issue by KSR-Yasuda** [tpope/vim-surround#361]
Could you support wide characters such as `『』` (U+300E, U+300F)?

In Unicode, the categories below are paired:

* [Open][Unicode_Ps]    / [Close][Unicode_Pe] Punctuation
* [Initial][Unicode_Pi] / [Final][Unicode_Pf] Punctuation

[Unicode_Ps]: https://www.compart.com/en/unicode/category/Ps
[Unicode_Pe]: https://www.compart.com/en/unicode/category/Pe
[Unicode_Pi]: https://www.compart.com/en/unicode/category/Pi
[Unicode_Pf]: https://www.compart.com/en/unicode/category/Pf

**Comment by pilgrimlyieu** [comment]
Firstly, use https://github.com/tomtomjhj/vim-surround which is equipped with #355 instead.

Then add the following code to your vimrc file.

```vim
let g:surround_{char2nr('q')}  = "『\r』"
```

Finally you can use `q` as a stand for `『...』`.

**Comment by KSR-Yasuda** [comment]
Okay, I'll try it. Thank you.
