### ISSUE TITLE
can't change to empty space anymore (VSCode)

### ISSUE THREAD

**Issue by dereknelson** [tpope/vim-surround#362]
i used to be able to change anything to a space (aka, deleting the object/quotes) like
`const something = {randomObject}` -> `cs{SPACE` -> `const something =  randomObject `  but it stopped working out of the blue. any ideas why?

**Comment by tpope** [comment]
VSCode? Wrong repo.

**Comment by dereknelson** [comment]
@tpope i appreciate the quick response. i downloaded surround for regular vim & it doesn't seem to work there either, would you mind re-opening the issue?
was surround supposed to support changing to spaces, or was it accidental? i would love to figure out how to get it back, it's crucial to my workflow

**Comment by tpope** [comment]
`<Space>` is special cased to _add_ a space. You might want `cs{<Space><Space>`.
