### ISSUE TITLE
How to not add whitespaces?

### ISSUE THREAD

**Issue by 0804d23d** [tpope/vim-surround#363]
I saw #27, but probably because I'm new to Vim, and also perhaps it's because something from `VimTeX` is interfering with `vim-surround`, I have settled with selecting the text I want to add a delimiter in visual mode, press `S` then whatever the delimiter in mind, but how can I get rid of the whitespaces added at the beginning and the end?

In #27, someone mentioned "use the close paren", but after reading the doc, I still have no idea what it means by "close paren". If it's the `change surrounding` mentioned in the doc `*cs*`, then even if `*cs*` can add a delimiter to whatever I have selected, it's not working for me because in either visual or insert mode, pressing `c` just remove the entire word selected (I'm using MacVIM).

So the only options that work for me are using `S` + delim, or `ysW(` (and similar). But both of them add whitespaces at the beginning and the end, which is really annoying.

**Comment by tpope** [comment]
> I still have no idea what it means by "close paren"

It's `)`.

> So the only options that work for me are using `S` + delim, or `ysW(`

That `(` is an "open paren". It's the thing you're supposed to replace with a "close paren".
