### ISSUE TITLE
Surrounding without spaces

### ISSUE THREAD

**Issue by amir-teymuri** [tpope/vim-surround#366]
How can the surrounding be done without spaces after and before brackets?
Currently when I do `ysiw(` with cursor on `w` I get `( world )`.

**Comment by lackovic** [comment]
> How can the surrounding be done without spaces after and before brackets?

Using an opening bracket will add a space, using a closing bracket will not add a space.

Examples:

- `ysiw(`  => `( world )`
- `ysiw)`  => `(world)`
