### ISSUE TITLE
Add full support for | ... | pipe brackets

### ISSUE THREAD

**Issue by myarcana** [tpope/vim-surround#367]
Some popular languages, e.g. ruby and rust, use `|one, two, three|`-esque expressions as common syntax.

`ds|` seems to work, deletes the surrounding `|` characters successfully, and `cs|)` also seems to work (changes them to other types of "surrounders"), as does `cs)|`.

However, `ysi|`, `ci|`, `vi|` all don't work.

**Comment by tpope** [comment]
Not a built-in, but you can create it yourself: see `:help surround-customizing`.

**Comment by myarcana** [comment]
Adding `let g:surround_124 = "|\r|"` (`char2r("|")` is 124) doesn't seem to change the behaviour of my editor. `ysiw|` still works just like before, but `ci|` still doesn't work

**Comment by tpope** [comment]
See `:help text-objects`. Specifically, note that it doesn't mention `i|` anywhere.

**Comment by Kache** [comment]
Adding a clarification b/c it wasn't clear to me right away: vim-surround doesn't define text objects like those, e.g. the same "issue" exists for `,` where you can `ds,` but not `ci,`.

However as mentioned in #305, a good alternative is [vim-textobj-between](https://github.com/thinca/vim-textobj-between) (see: https://github.com/kana/vim-textobj-user/wiki).
