### ISSUE TITLE
Surround

### ISSUE THREAD

**Issue by ahshah** [tpope/vim-surround#368]
Is it possible add a configuration option for surround to skip newlines? Or would such a patch be welcome?

I find my self doing alot of 'v$S)' on single lines, and '$' is alot easier than 'g_'

**Comment by tpope** [comment]
Shouldn't be necessary. Try `yss)`.

**Comment by ahshah** [comment]
Thanks for the quick reply- I was not very clear in my initial ticket. I'm trying to visually select in the middle of a line:
With my cursor here:

![HelloWorldCursor](https://user-images.githubusercontent.com/1134779/204347377-fd3be67c-f3cb-411c-b459-31ce41fd106b.jpg)

I'd like to surround via `v$S)`
![HelloWorldSurround](https://user-images.githubusercontent.com/1134779/204347374-79d2f86d-32a7-481a-bb16-7103245fa2b5.jpg)

To achieve:
![HelloWorldComplete](https://user-images.githubusercontent.com/1134779/204347952-9d9f66ce-4e2d-44ff-97f8-083a50864ea6.jpg)

`yss)` would surround only when selecting the full line. Is there a better way to doing this? trying to avoid `vg_S)` as its a bit unwieldy

**Comment by tpope** [comment]
`ys$)` would work here.

To address the spirit of the question, I am disinclined to take on the maintenance burden of this proposed configuration option.
