### ISSUE TITLE
How can I delete text between delimiters?

### ISSUE THREAD

**Issue by Flimm** [tpope/vim-surround#372]
Let's say I have this text:

    print("Hello world!")

and my cursor position is in the middle, by the `o`, for example. I would like to end up with this text:

    print("")

How can I delete the text in between delimiters? Pressing `ds"` deletes the quotation marks, but doesn't delete `Hello world!`.

Similarly, how can I end up with this text?

    print()

**Comment by martintraverso** [comment]
Hi @Flimm This is possible to achieved with native vim:
`di"`
will result in:
`print("")`
and
`di(`
will result in:
`print()`

**Comment by Flimm** [comment]
Thank you so much!

Also, I found out that if I want to delete everything including the delimetars, I can use `da"` or `da(`. For example, if I start with `print("Hello world!")` with the cursor in the middle, typing `da(` will give me:

    print

For more help, look at: `:help motion.txt` and `:help v_i"`
