### ISSUE TITLE
Feature request: Treat self-closing XML/HTML tags as <>

### ISSUE THREAD

**Issue by ebrannin-bw** [tpope/vim-surround#376]
## Steps to reproduce

1. Make a new document:
  ```xml
<outer>
<inner />
</outer>
```
2. Put the cursor in the middle of `<inner />`: `/inn`
3. Type `ysat<middle>` (not shown below) or ``ysat<C-T>middle>` (shown)

## Expected result:

```xml
<outer>
<middle>
  <inner />
</middle>
</outer>
```

## Observed result
```xml
<middle>
  <outer>
  <inner />
  </outer>
</middle>
```

## Workaround

`ysa<<middle>` or `ysa<<C-T>middle>`

## Background

Self-closing tags come up in [HTML5](http://xahlee.info/js/html5_non-closing_tag.html), [XML](https://stackoverflow.com/questions/7231902/self-closing-tags-in-xml-files), [React](https://react.dev/learn/writing-markup-with-jsx#2-close-all-the-tags), etc.

I was just turning a React component from a flex-row into a table, and as I wrapped each element with `<td>` I had to switch between `ysat` and `ysa<` depending on if it was self-closing or not.

**Comment by tpope** [comment]
I think I agree. However, surround.vim is merely delegating to  Vim's built-in `at` operator. You can see the same behavior if you do `dat` or `gUat`.

And I don't plan on breaking with Vim here. You could try floating your proposal to Vim itself, but I doubt it would be considered due to backwards compatibility concerns.

**Comment by ebrannin-bw** [comment]
Makes sense, thanks!

**Comment by ebrannin-bw** [comment]
Looks like vim has [already documented this](https://vimdoc.sourceforge.net/htmldoc/motion.html#tag-blocks):

> `"<aaa/>"` items are skipped.  Case is ignored, also for XML where [case](https://vimdoc.sourceforge.net/htmldoc/change.html#case) does matter.

Sounds like what I really want is a custom text-object plugin to declare something like `aT` and `iT` (or whatever, but it seems like those aren't built-in) -- I'll update here if I find one already exists or (_very_ eventually) figure out how to write one.

**Comment by tpope** [comment]
> Sounds like what I really want is a custom text-object plugin

Yes, but see #355.

**Comment by tpope** [comment]
Oops, I meant to link to https://github.com/tpope/vim-surround/issues/329#issuecomment-922978875.
