### ISSUE TITLE
Feature Request: cS

### ISSUE THREAD

**Issue by sjl** [tpope/vim-surround#48]
It would be handy to have a cS command that acts like yS by putting the resulting text on its own line.

For example:

    results = Entry.objects.filter(title='foo', author='bob').count()
                                      ^
                                      |
                                      Cursor
Press `cSbb` and get:

    results = Entry.objects.filter(
        title='foo', author='bob'
    ).count()

**Comment by jwhitley** [comment]
FYI, this has been implemented on my fork.  See the referenced PR, above, for details. It's a pretty modest change in keeping with the existing `yS` functionality.
