### ISSUE TITLE
add #ifdef ... #endif support

### ISSUE THREAD

**Issue by ccxcz** [tpope/vim-surround#57]
It would be convenient for C and C++ programmers to have `#ifdef VALUE\r...\r#endif`  preprocessor directive support. It is very commonly used for both commenting code `#ifdef 0` and checking for platform features to make the code portable.

**Comment by markwal** [comment]
BTW, for others who land here via Google.  The following custom replacement will prompt for the MACRO and surround with #ifdef MACRO #endif // MACRO.  For example, select visual linewise three lines and surround: VjjS

let g:surround_{char2nr("i")} = "#ifdef \1ifdef token: \1\r#endif // \1\1"
