### ISSUE TITLE
yss(

### ISSUE THREAD

**Issue by bybor** [tpope/vim-surround#6]
Not sure about it

Have a line
    "Exclaim"
Type
    yss(
Result
    ( "Exclaim" )
Type
    yss)
    or
    yssb
Result
    ("Exclaim")
From documentation
    Eight punctuation marks, (, ), {, }, [, ], <, and >, represent themselves
    and their counterparts.  If the opening mark is used, contained whitespace is
    also _trimmed_.  The targets b, B, r, and a are aliases for ), }, ], and >
    (the first two mirror Vim; the second two are completely arbitrary and 
    subject to change).

_trimmed_ caused a question for me when i finally figured out how to add braces without extra space

These lines may refer to change and delete use cases and not adding surrounding, but not very clear.

**Comment by lockejan** [comment]
> Eight punctuation marks, (, ), {, }, [, ], <, and >, represent themselves
and their counterparts. If the opening mark is used, contained whitespace is
also trimmed. 

Hey, isn't this a contradiction?
`The opening mark` is in my understanding `(, [ and {` 
However, the plugin behaves the other way around.
ysw) results in (foo)
and
ysw( in ( foo )
in my case.

What am I missing or is this a very old flaw in the readme?🤔

**Comment by tpope** [comment]
You're quoting the section on targets, but testing the behavior of replacements, which is deliberately the opposite.

**Comment by lockejan** [comment]
> You're quoting the section on targets, but testing the behavior of replacements, which is deliberately the opposite.

Well that makes sense in some way to me, but then I'm still missing the section for "add surroundings" in the docs.
The closest to that is in my interpretation the "yank surround" part, while "change surround" is mostly mentioned within the context of replacing surroundings. 
I would hope for a clearer distinction between such then.
