### ISSUE TITLE
Keeping the attributes in HTML tags

### ISSUE THREAD

**Issue by danielepolencic** [tpope/vim-surround#95]
Hello,

Let's say I have a tag (and cursor at *):

    <h1 class="blah" id="moo">H*ello!</h1>

I want to change it to:

    *<h2 class="blah" id="moo">Hello</h2>

i.e. Change the type of tag, but keep all the elements.

Using surround.vim, I could do:

    cst<h2>

but that changes the HTML to:

    *<h2>Hello</h2>

Is just changing the tag possible, but keeping all the attributes?

Thanks
Daniele

**Comment by sassanh** [comment]
@shanesmith Unfortunately it's not "dot"able, pressing dot will redo it but removes attributes too.

**Comment by Flimm** [comment]
This behaviour doesn't seem to work for me any more.
